# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171017_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 9, 0, 24, 289718, tzinfo=utc)),
        ),
    ]
