# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171009_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='intind',
            name='max_critical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intind',
            name='min_critical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realind',
            name='max_critical',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realind',
            name='min_critical',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 17, 17, 54, 624388, tzinfo=utc)),
        ),
    ]
