# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171012_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 21, 9, 59, 191153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('DOCTOR', 'DOCTOR')], max_length=20),
        ),
    ]
