# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('I', 'первая'), ('II', 'вторая'), ('III', 'третья'), ('IV', 'четвертая')], max_length=20, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
        migrations.AddField(
            model_name='patient',
            name='omi_card',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='OMI Card'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rh_factor',
            field=models.CharField(blank=True, choices=[('positive', 'Rh+'), ('negative', 'Rh-')], max_length=20, null=True, verbose_name='RH Factor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'мужской'), ('FEMALE', 'женский')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 28, 22, 37, 20, 312438, tzinfo=utc)),
        ),
    ]
