# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171009_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 22, 30, 48, 995588, tzinfo=utc)),
        ),
    ]
