# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170930_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrec',
            old_name='int_indicators',
            new_name='int_inds',
        ),
        migrations.RenameField(
            model_name='testrec',
            old_name='real_indicators',
            new_name='real_inds',
        ),
        migrations.RenameField(
            model_name='testrec',
            old_name='text_indicators',
            new_name='text_inds',
        ),
        migrations.AlterField(
            model_name='patient',
            name='rh_factor',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Rh+'), ('NEGATIVE', 'Rh-')], max_length=20, null=True, verbose_name='RH Factor'),
        ),
        migrations.AlterField(
            model_name='testrec',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_recs', to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 11, 27, 45, 216452, tzinfo=utc)),
        ),
    ]
